print('1-mixin is a class ')
print('2- it is parent class of object')
print('3-there is no use of mixin')
print('4-it is going to expand the code')
print('5 it is going to consume the code')
print('6 it is sixth line of the code')
print('7 th line of the code')
print('8th line of the code')
print('9th line of the code')
print('10 line of the code')